name: shoping_cart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dartz: ^0.10.1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dio: ^5.3.3
  get_it: ^7.6.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  retrofit_generator:
  build_runner: 
  json_serializable:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

